resources:
  - name: ans_repo
    type: sourceControl/GitRepo
    syntaxVersion: 1.0.0
    configuration:
      GitHub : manishas_jfrog
      gitUrl: https://github.com/manishas-jfrog/extension_sample.git
      gitBranch: main
      gitRepoName: extension_sample

pipelines:
  - name: ans_pipeline
    steps:
      - name: ansible_step_v1
        type: ansible/ansiblePlaybook
        syntaxVersion: 1.0.0
        configuration:
          resourceName: ans_repo
          fileName: ./ansible.yml
          inputResources:
            - name: ans_repo
        execution:
          onStart:
            - echo "Starting execution of ansible playbook..."
          onComplete:
            - echo "Completed execution of ansible playbook"

      - name: ansible_step_latest
        type: ansible/ansiblePlaybook
        syntaxVersion: latest
        configuration:
          fileName: ./ansible.yml
          inputResources:
            - name: ans_repo
              trigger: false
          inputSteps:
            - name: ansible_step_v1
